CREATE TABLE IF NOT EXISTS Users(
  id INT PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30),
  email VARCHAR(40) UNIQUE NOT NULL,
  phone_number VARCHAR(15) UNIQUE DEFAULT NULL,
  country VARCHAR(20) DEFAULT NULL,
  country_code VARCHAR(5) DEFAULT NULL,
  otp_code VARCHAR(6) NULL,
  password VARCHAR(225) DEFAULT NULL,
  provider ENUM("local","google"),
  `role` ENUM("admin", "user") DEFAULT "user",
  image_url TEXT DEFAULT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Category(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(30) UNIQUE NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Lecture(
  id INT PRIMARY KEY AUTO_INCREMENT,
  category_id INT NOT NULL,
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL, 
  sound_url TEXT NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES Category(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Save_lecture(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  lecture_id INT NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY (lecture_id) REFERENCES Lecture(id) ON DELETE CASCADE
) ENGINE=InnoDB;



